## must be run manually to push image
name: Build and Push Image
on:
  workflow_dispatch:
    inputs:
      token:
        description: "Personal Access Token to use for Github Container Registry authentification"
        required: true
jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with: 
        username: ${{ github.actor }}
        password: ${{ github.events.inputs.token }}
        registry: ghcr.io
    - name: Build and Push Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: "rem1776/fre-nctools-container/fre-nctools-base:1.0"
