## must be run manually to push image
name: Build and Push Image
on: workflow_dispatch
jobs:
  push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v2
    - name: Build and Push Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: NOAA-GFDL/FRE-NCtools-container/fre-nctools-base
        tag_with_ref: true
